codecov:
  require_ci_to_pass: true

coverage:
  status:
    project:
      adapter:
        flags: [ "adapter" ]
      construct:
        flags: [ "construct" ]

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false