body:
- type: markdown
  attributes:
    value: |
      Be sure to comfirm that your question is not duplicated by searching.

- type: textarea
  attributes:
    label: What's your question?
    description: |
      Please describe your question here.

- type: input
  attributes:
    label: What's your local envirments?
    description: |
      Please describe your local envirments, such as OS, Node.js version, Package version etc. It's not required, if your question is not related to development.
    value: |
      1. os:
      2. node-version:
      3. package-version:
      4. ...
  validations:
    required: false
