title: "Please input a title for your question"
body:
- type: markdown
  attributes:
    value: |
      Please describe your question here.

- type: textarea
  attributes:
    label: What's your local envirments?
    description: |
      Please describe your local envirments, such as OS, Node.js version, Package version etc. It's not required, if your question is not related to development.
  validations:
    required: false
