body:
- type: textarea
  attributes:
    label: What's your question?
    description: |
      Please describe your question here
  validations:
    required: true

- type: textarea
  attributes:
    label: What's your local envirments?
    description: |
      Please describe your local envirments. It's not required, if your question is not related to programming
    value: |
      1. os:
      2. node:
      3. astrojs-aws:
      ...
    render: bash
