name: Bug report
description: Report a bug in astrojs-aws.
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Sanity checks
    options:
    - label: "I have searched [github.com/helbing/astrojs-aws/issues](https://github.com/helbing/astrojs-aws/issues?q=) and there are no duplicates of my issue"
      required: true
    - label: "I would like to work on this."
- type: textarea
  attributes:
    label: Please describe the bug
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
  validations:
    required: true

- type: textarea
  attributes:
    label: Actual Behavior
  validations:
    required: true

- type: textarea
  attributes:
    label: What's your local envirments?
    value: |
      1. os:
      2. node:
      3. astrojs-aws:
      ...
    render: bash
  validations:
    required: true

- type: textarea
  attributes:
    label: How to reproduce it?
  validations:
    required: false
