blank_issues_enabled: false
contact_links:
- name: Community communication
  about: Chat about anything and everything here.
  url: https://github.com/helbing/astrojs-aws/discussions/new?category=general

- name: Q&A
  about: Please ask and answer questions as a discussion thread.
  url: https://github.com/helbing/astrojs-aws/discussions/new?category=q-a

