name: docs

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - uses: pnpm/action-setup@v2
      with:
        run_install: true
    - run: pnpm run build --filter @astrojs-aws/docs
