name: docs

on:
  pull_request:
    types:
    - closed
  push:
    branches:
    - main
    tags:
    - 'v*'

jobs:
  publish-staging:
    name: Docs preview
    runs-on: ubuntu-latest
    if: ${{ github.head_ref == 'main' && github.event.pull_request.merged == true }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0
    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
    - run: cd docs && hugo --minify

    - uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: docs/public

  publish-production:
    name: Docs publish
    runs-on: ubuntu-latest
    #if: ${{ github.head_ref == 'main' || startsWith(github.ref, 'refs/tags/') }} # temporary
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
        fetch-depth: 0

    - uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'

    # - uses: actions/setup-node@v3
    #   with:
    #     node-version-file: '.nvmrc'

    - uses: amondnet/vercel-action@v20
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-args: '--prod'
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: docs/public
